# "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#"By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."


def f(n):
    if n==0:
        return(1)
    elif n==1:      
        return(1)
    else:
        return(f(n-1)+f(n-2))
l=0
for i in range(2,30,3):
    #if(f(i)%2==0):
    #l.append(f(i))
    #l.append(f(i))
    l=l+f(i)

print(l)